[oauth]
client_id = "141742353498-5geiqu2biuf2s81klgau6qjsjve9fcrc.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://certificate-generator-1.streamlit.app/"

[database]
db_path = "users.db"
